backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth', 'role']);

Route::group(['middleware' => ['auth', 'role']], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
});

Route::group(['middleware' => ['auth', 'role'], 'namespace' => 'Admin'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('user/show/{id}', 'UserController@show')->name('user.show');
	Route::put('user/active/{id}', 'UserController@active')->name('user.active');
	Route::put('user/inactive/{id}', 'UserController@inactive')->name('user.inactive');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group([
    'namespace' => 'Admin',
	'middleware' => ['auth', 'role']    
], function () {
	Route::get('article', 'ArticleController@index')->name('article.index');
	Route::get('article/show', 'ArticleController@show')->name('article.show');
	Route::put('article/active/{id}', 'ArticleController@active')->name('article.active');
	Route::put('article/inactive/{id}', 'ArticleController@inactive')->name('article.inactive');
	Route::put('article/rate/reset/{id}', 'ArticleController@reset')->name('article.rate.reset');
	Route::delete('article/delete/{id}', 'ArticleController@destroy')->name('article.destroy');
});

Route::group([
	'middleware' => ['auth', 'role'],
    'namespace' => 'Admin'
], function () {
	Route::get('comment', 'CommentController@index')->name('comment.index');
	Route::get('comment/show/{id}', 'CommentController@show')->name('comment.show');
	Route::put('comment/accept/{id}', 'CommentController@accept')->name('comment.accept');
	Route::put('comment/reject/{id}', 'CommentController@reject')->name('comment.reject');
});

Route::group([
	'middleware' => ['auth', 'role'],
    'namespace' => 'Admin'
], function () {
	Route::get('category', 'CategoryController@index')->name('category.index');
	Route::get('category/create', 'CategoryController@create')->name('category.create');
	Route::get('category/edit/{id}', 'CategoryController@edit')->name('category.edit');
	Route::post('category/store', 'CategoryController@store')->name('category.store');
	Route::put('category/update/{id}', 'CategoryController@update')->name('category.update');
	Route::delete('category/delete/{id}', 'CategoryController@destroy')->name('category.destroy');
});

backend/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    const ADMIN = 'admin';
    const MODERATOR = 'moderator';
    const AUTHOR = 'author';    
    const USER = 'user';

    const ACTIVE = 'active';
    const INACTIVE = 'inactive';
    const MODERATED = 'moderated';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'email', 'password', 'login', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
    */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
      * Return a key value array, containing any custom claims to be added to the JWT.
      *
      * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * Get user articles.
     */

    public function articles()
    {
        return $this->hasMany('App\Article', 'user_id', 'id');
    } 

    /**
     * Get user likes.
     */

    public function likes()
    {
        return $this->hasMany('App\Like', 'user_id', 'id');
    }

    /**
     * Get user comments.
     */

    public function comments()
    {
        return $this->hasMany('App\Comment', 'user_id', 'id');
    }


    /**
     * Get roles filter.
     *
     * @return array
     */

    public function getRolesFilter()
    {
        return [
            self::ADMIN   => 'Админиcтраторы',
            self::MODERATOR => 'Модераторы',
            self::AUTHOR  => 'Авторы',
            self::USER  => 'Пользователи'
        ];        
    }

}

backend/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Requests\Admin\UserActiveRequest;
use App\Http\Requests\Admin\UserInactiveRequest;
use App\Entities\User\Dto\ActiveUserDto;
use App\Entities\User\Dto\InactiveUserDto;
use App\Entities\User\Service\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    private $userService;
    private $request;

    function __construct(UserService $userService, Request $request)
    {
        $this->userService = $userService;
        $this->request = $request;
    } 

    public function index(User $userModel)
    {
        $roles = $this->userService->displayRolesFilter();
        $users = $this->userService->filter($this->request->role);
        return view('users.index', [
            'users' => $users,
            'roles' => $roles
        ]);
    }

    public function show()
    {
        $user = $this->userService->displayUser($this->request->id);

        return view('users.show', [
            'user'  => $user
        ]);
    }

    public function active(string $id, UserActiveRequest $request)
    {
        $dto = new ActiveUserDto($id, $request->note);

        $this->userService->activateUser($this->request->id);
        return redirect()->route('user.index')->withStatus(__('Пользователь активирован!'));
    }

    public function inactive(string $id, UserInactiveRequest $request)
    {
        $dto = new InactiveUserDto($id, $request->reason);

        $this->userService->inactivateUser($this->request->id);
        return redirect()->route('user.index')->withStatus(__('Пользователь деактивирован!'));
    }

    public function create()
    {
        if (auth()->user()->role === 'admin') {
            return view('users.create');               
        }                                     
        return abort(403);
    }                                                          

    public function store(UserRequest $request, User $model)
    {
        $model->create([
            'name' => $request->name,
            'surname' => $request->surname,
            'email' => $request->email,
            'login' => $request->login,
            'password' => Hash::make($request->password),
            'role' => $model::MODERATOR,

        ]);

        return redirect()->route('user.index')->withStatus(__('Модератор успешно создан.'));
    }

    public function edit(User $user)
    {
        if ($user->role == User::ADMIN) {
            return redirect()->route('user.index')->withStatus(__('Вы не можете редактировать администратора.'));
        }

        return view('users.edit', compact('user'));
    }

    public function update(UserRequest $request, User  $user)
    {
        $hasPassword = $request->get('password');
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$hasPassword ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('Пользователь успешно обновлен.'));
    }

    public function destroy(User  $user)
    {

        if (auth()->user()->role !== $user::ADMIN) {
            return redirect()->route('user.index')->withStatus(__('У вас нет прав на это действие!'));
        }

        $this->userService->destroyUser($user->id);

        return redirect()->route('user.index')->withStatus(__('Пользователь успешно удален.'));
    }
}

backend/resources/views/users/create.blade.php
@extends('layouts.app', ['page' => __('Управление пользователями'), 'pageSlug' => 'users'])

@section('content')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Добавить модератора') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Вернуться к списку') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Информация о модераторе') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Имя') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Имя') }}" value="{{ old('name') }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-surname">{{ __('Фамилия') }}</label>
                                    <input type="text" name="surname" id="input-surname" class="form-control form-control-alternative{{ $errors->has('surname') ? ' is-invalid' : '' }}" placeholder="{{ __('Фамилия') }}" value="{{ old('surname') }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'surname'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-login">{{ __('Логин') }}</label>
                                    <input type="text" name="login" id="input-login" class="form-control form-control-alternative{{ $errors->has('login') ? ' is-invalid' : '' }}" placeholder="{{ __('Логин') }}" value="{{ old('login') }}" required>
                                    @include('alerts.feedback', ['field' => 'login'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>
                                    @include('alerts.feedback', ['field' => 'email'])
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Пароль') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Пароль') }}" value="" required>
                                    @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Подтверждение пароля') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Подтверждение пароля') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Добавить') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/users/index.blade.php
@extends('layouts.app', ['page' => __('Управление пользователями'), 'pageSlug' => 'users'])

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title">{{ __('Пользователи') }}</h4>
                        </div>
                        @if(auth()->user()->role === 'admin')
                        <div class="col-4 text-right">
                            <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Добавить модератора') }}</a>
                        </div>
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    @include('alerts.success')
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Фильтр
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a 
                              class="dropdown-item" href="{{ route('user.index', ['role' => null]) }}">Все участники регаты  
                          </a>
                          @foreach ($roles as $role => $value )
                            <a 
                                class="dropdown-item" href="{{ route('user.index', ['role' => $role]) }}">{{ $value }}
                            </a>
                          @endforeach
                      </div>
                    </div>
                    <div class="">
                        <table class="table tablesorter " id="">
                            <thead class=" text-primary">
                                <th scope="col">{{ __('Имя') }}</th>
                                <th scope="col">{{ __('Фамилия') }}</th>
                                <th scope="col">{{ __('Логин') }}</th>
                                <th scope="col">{{ __('Email') }}</th>
                                <th scope="col">{{ __('Дата создания') }}</th>
                                <th scope="col">{{ __('Статус') }}</th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->surname }}</td>
                                        <td>{{ $user->login }}</td>
                                        <td>
                                            <a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                        <td>{{ $user->created_at->format('d.m.Y H:i') }}</td>
                                        <td>{{ $user->status }}</td>
                                        <td class="text-right">
                                                <div class="dropdown">
                                                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        @if (auth()->user()->role === 'admin' )
                                                            <a class="dropdown-item" href="{{ route('user.show', ['id' => $user->id] ) }}">{{ __('Просмотр.') }}</a>
                                                            <a class="dropdown-item" href="{{ route('comment.index', ['user' => $user->id])}}">{{ __('Комментарии') }}</a>
                                                            <form action="{{ route('user.destroy', $user) }}" method="post">
                                                                @csrf
                                                                @method('delete')

                                                                <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                                                            {{ __('Удалить') }}
                                                                </button>
                                                            </form>
                                                        @else
                                                            <a class="dropdown-item" href="{{ route('user.show', ['id' => $user->id] ) }}">{{ __('Просмотр.') }}</a>
                                                            <a class="dropdown-item" href="{{ route('comment.index', ['user' => $user->id])}}">{{ __('Комментарии') }}</a>
                                                        @endif
                                                    </div>
                                                </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer py-4">
                    <nav class="d-flex justify-content-end" aria-label="...">
                        {{ $users->links() }}
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/users/show.blade.php
@extends('layouts.app', ['page' => __('Управление пользователями'), 'pageSlug' => 'users'])

@section('content')
  <div class="card">
    <div class="card-body">
      <h3>Статус: {{$user->status}}</h3>
      <form>
        <div class="form-group">
          <label for="name">Имя</label>
          <input disabled="true" type="text" class="form-control" id="name" value="{{$user->name}}" placeholder="Имя" name="name" >
        </div>
        <div class="form-group">
          <label for="surname">Фамилия</label>
          <input disabled="true" type="text" class="form-control" id="surname" value="{{$user->surname}}" placeholder="Фамилия" name="surname" >
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input disabled="true" type="email" class="form-control" id="email" placeholder="Email" value="{{$user->email}}" name="email">  
        </div>
      </form>
      <div class="row">
        <div class="col-md-6">
          <form method="post" action="{{route('user.active', ['id' => $user->id])}}">
            @csrf
            @method('put')
              <div class="form-group">
                  <label for="note">Пожелания:</label>
                  <textarea class="form-control" id="note" name="note" rows="3">
                    
                  </textarea>
                  <button type="submit" class="btn btn-success">Принять</button>
              </div>
          </form>
        </div>
        <div class="col-md-6">
          <form method="post" action="{{route('user.inactive', ['id' => $user->id])}}">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="reason">Причина бана:</label>
                <textarea class="form-control" id="reason" name="reason" rows="3">
                  
                </textarea>
                <button type="submit" class="btn btn-danger">Отклонить</button>
            </div>
          </form>             
        </div>
      </div>
    </div>
  </div>
@endsection